docs: mark as optional property "animated" of AnimationOption
Property "animated" is not required by View's "hide" and "show" methods.
Also it will cause errors in TypeScript declaration file (if you'll try
to build one from docs) for methods "hide" and "show" of
"Titanium.UI.iPad.Popover" class.

```typescript

declare interface AnimationOption {
    animated?: boolean;  // "animated: boolean;" will cause "Error TS2416"
}

declare interface PopoverParams {
    animated?: boolean;
    rect?: Dimension;
    view: Titanium.UI.View;
}

class View extends Titanium.Proxy {
    hide(options?: AnimationOption): void;
    show(options?: AnimationOption): void;
}

class Popover extends Titanium.UI.View {
    hide(options: PopoverParams): void;
    show(params: PopoverParams): void;
}
```